service: snap

plugins:
  - serverless-plugin-chrome
  - serverless-offline
  - serverless-webpack
  - serverless-apigw-binary


provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1536
  timeout: 180

functions:
  app:
    handler: src/serverless.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      DEBUG: 0
      HOME: /var/task

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"

custom:
  webpack:
    includeModules: true
  apigwBinary:
    types:
      - '*/*'